### ISSUE TITLE
Is there currently anyway to programatically expand a specific row on load?

### ISSUE THREAD

**Issue by alexanderyhapcv** [madmax983/Lightning-Data-Grid#46]

**Comment by madmax983** [comment]
With the way it is currently setup, when you click on the Chevron a childToggle event is fired. This event is then handled in the data grid component to do the expanding and collapsing.

With the event being a component type, and not an application one, I don't believe you'll be able to fire it from above the hierarchy and have it be handled. 

So the shorter answer is not right now, since that event is of a component type.

Two options to address this:

1. Make the event an application type. 
2. Expose a public method on the grid, and bypass the event for this use case. I think this is my preferred solution. Something like grid.expand(row)

**Comment by madmax983** [comment]
As I was working on #47 this weekend I realized there is a way to do this, and you can see an example in the tests. Check out the [child toggle test](https://github.com/madmax983/Lightning-Data-Grid/blob/fe6fec43247d4583a255843cd7d705e723367d24/force-app/test/default/staticresources/lightningDataGridTests.resource#L89)

It's a bit convoluted to be doing outside of a test, but if this was blocking you, it could be done as a workaround. There should totally be an easier way of doing this at the row level, and not the cell.
